# Generated by Django 3.0.2 on 2020-01-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
