# Generated by Django 3.0.2 on 2020-02-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0002_job_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='photo',
            field=models.ImageField(blank=True, default='/media/unavailable.jpg', null=True, upload_to='media/'),
        ),
    ]
