# Generated by Django 3.0.2 on 2020-02-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0003_auto_20200205_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='photo',
            field=models.ImageField(default='/media/unavailable.jpg', null=True, upload_to='media/'),
        ),
    ]
