# Generated by Django 3.0.2 on 2020-02-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0004_auto_20200205_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('img', models.ImageField(default='/media/unavailable.jpg', null=True, upload_to='media/')),
            ],
        ),
    ]
