# Generated by Django 3.0.2 on 2020-02-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0005_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
