# Generated by Django 3.0.2 on 2020-02-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0006_auto_20200207_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='projects',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
